version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: log-symbols
    versions:
    - 4.1.0
  - dependency-name: jsdom
    versions:
    - 16.5.2
  - dependency-name: type-fest
    versions:
    - 1.0.1
  - dependency-name: eslint-config-xo
    versions:
    - 0.35.0
  - dependency-name: "@types/jsdom"
    versions:
    - 16.2.9
  - dependency-name: "@fortawesome/fontawesome-svg-core"
    versions:
    - 1.2.34
    - 1.2.35
  - dependency-name: next-ignite
    versions:
    - 0.10.7
    - 0.10.8
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.2
    - 4.16.1
    - 4.17.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.5
    - 24.1.9
    - 24.2.1
  - dependency-name: "@octokit/rest"
    versions:
    - 18.3.0
    - 18.3.1
    - 18.3.4
  - dependency-name: ts-jest
    versions:
    - 26.5.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 32.2.0
  - dependency-name: vsce
    versions:
    - 1.85.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.31
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
